server:
  port : 8081
spring:
  jpa:
     hibernate:
        ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/employee_details
    username: root
    password: iamyosuva
    driver-class-name: com.mysql.cj.jdbc.Driver
